c_stdlib_version:   # [osx and x86_64]
  - 10.15           # [osx and x86_64]

# need to override CUDA because pytorch 2.4 doesn't have builds for 12.6
cuda_compiler_version:      # [linux]
  - None                    # [linux]
  - 11.8                    # [linux64]
  - 12.0                    # [linux]
# need to override rest of zip to make smithy happy
c_compiler_version:         # [linux]
  - 13                      # [linux]
  - 11                      # [linux64]
  - 12                      # [linux]
cxx_compiler_version:       # [linux]
  - 13                      # [linux]
  - 11                      # [linux64]
  - 12                      # [linux]
fortran_compiler_version:   # [linux]
  - 13                      # [linux]
  - 11                      # [linux64]
  - 12                      # [linux]
cuda_compiler:              # [linux]
  - None                    # [linux]
  - nvcc                    # [linux64]
  - cuda-nvcc               # [linux]
docker_image:                                            # [linux]
  - quay.io/condaforge/linux-anvil-x86_64:alma9          # [linux]
  - quay.io/condaforge/linux-anvil-x86_64-cuda11.8:ubi8  # [linux64]
  - quay.io/condaforge/linux-anvil-x86_64:alma9          # [linux]    
# end override of monster zip
