{% set tests_to_skip = "test_url_is_accessible" %}
{% set version = "0.10.1" %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: torchvision-split
  version: {{ version }}

source:
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: 4d595cf0214c8adc817f8e3cd0043a027b52b481e05d67b04f4947fcb43d4277
  patches:
    # compatibility with pillow >=8.3.0,<8.3.2; can be dropped once 8.3.2 arrives (then update range below!)
    - patches/0001-Don-t-check-transparency-channel-for-pil-8.3-in-test.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}

outputs:
  - name: torchvision
    script: build-torch.sh  # [not win]
    script: build-torch.bat  # [win]
    build:
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torch_proc_type }}  # [cuda_compiler_version == "None"]
      string: py{{ CONDA_PY }}cuda{{ cuda_compiler_version|replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torch_proc_type }}  # [cuda_compiler_version != "None"]
      run_exports:
        # ensure matching proc-type
        - torchvision =*=*_{{ torch_proc_type }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
        - sysroot_linux-64 ==2.17                # [linux64]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pytorch =*={{ torch_proc_type }}*      # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
        - cudnn                                  # [cuda_compiler_version != "None"]
        # split off image/video into separate outputs?
        - jpeg
        - libpng
        # ffmpeg
        - numpy
        # exclude 8.3.0 specifically due to pytorch/vision#4146, python-pillow/Pillow#5571
        - pillow >=5.3.0,!=8.3.0
        - pytorch
        - pytorch-gpu                           # [cuda_compiler_version != "None"]
        - pytorch-cpu                           # [cuda_compiler_version == "None"]
      run:
        - python
        - pytorch
        - pytorch-gpu                            # [cuda_compiler_version != "None"]
        - pytorch-cpu                            # [cuda_compiler_version == "None"]
        - {{ pin_compatible('cudnn') }}          # [cuda_compiler_version != "None"]
        - {{ pin_compatible('numpy') }}
        - pillow >=5.3.0,!=8.3.0

    test:
      requires:
        - pytest
        - av
        - requests
        - scipy
      source_files:
        - test
      imports:
        - torchvision
        - torchvision.datasets
        - torchvision.models
        - torchvision.transforms
        - torchvision.utils
      commands:
        # skip test_url_is_accessible instead of hitting 20+ servers per run, since
        # each server might be occasionally unresponsive and end up failing our CI
        {% set tests_to_skip = "test_url_is_accessible" %}
        # osx warns with nnpack if there is no AVX2, see conda-forge/pytorch-cpu-feedstock#56
        {% set tests_to_skip = tests_to_skip + " or test_adjust_sharpness" %}  # [osx]
        - pytest -k "not ({{ tests_to_skip }})" test/

about:
  home: http://pytorch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  dev_url: https://github.com/pytorch/vision
  doc_url: http://pytorch.org/docs/master/torchvision

extra:
  recipe-maintainers:
    - nehaljwani
    - hmaarrfk
    - h-vetinari
  feedstock-name: torchvision
