{% set version = "0.9.1" %}
{% set number = 1 %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: torchvision-split
  version: {{ version }}

source:
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: 79964773729880e0eee0e6af13f336041121d4cc8491a3e2c0e5f184cac8a718
  patches:
    # partially backport (and adapt) pytorch/vision#3631, can be dropped for v>=0.10.0
    - patches/0001-avoid-check-if-pil-version-is-8.2-as-the-reference-i.patch

build:
  number: {{ number }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}

outputs:
  - name: torchvision
    script: build-torch.sh   # [not win]
    script: build-torch.bat  # [win]
    build:
      string: "py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ number }}_{{ torch_proc_type }}"                                                  # [cuda_compiler_version == "None"]
      string: "py{{ CONDA_PY }}cuda{{ cuda_compiler_version|replace('.', '') }}h{{ PKG_HASH }}_{{ number }}_{{ torch_proc_type }}"  # [cuda_compiler_version != "None"]
      run_exports:
        # ensure matching proc-type
        - torchvision =*=*_{{ torch_proc_type }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
        - sysroot_linux-64 ==2.17                # [linux64]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pytorch =*={{ torch_proc_type }}*      # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
        - cudnn                                  # [cuda_compiler_version != "None"]
        # split off image/video into separate outputs?
        - jpeg
        - libpng
        # ffmpeg
        - numpy
        - pillow >=4.1.1,<8.3
        - pytorch >=1.8.0={{ torch_proc_type }}*
      run:
        - python
        - pytorch >=1.8.0={{ torch_proc_type }}*
        - {{ pin_compatible('cudnn') }}          # [cuda_compiler_version != "None"]
        - {{ pin_compatible('numpy') }}
        - pillow >=4.1.1,<8.3

    test:
      requires:
        - pytest
        - requests
        - scipy
      source_files:
        - test
      imports:
        - torchvision
        - torchvision.datasets
        - torchvision.models
        - torchvision.transforms
        - torchvision.utils
      commands:
        # skip test_url_is_accessible instead of hitting 20+ servers per run, since
        # each server might be occasionally unresponsive and end up failing our CI
        - pytest -k "not test_url_is_accessible" test/

  # for compatibility with (& ease of migration from) old packages in the pytorch channel, see
  # https://anaconda.org/pytorch/torchvision-cpu/files
  - name: torchvision-cpu
    build:
      skip: true  # [cuda_compiler_version != "None"]
    requirements:
      run:
        - torchvision ={{ version }}=*_cpu
    test:
      imports:
        - torchvision

about:
  home: http://pytorch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  dev_url: https://github.com/pytorch/vision
  doc_url: http://pytorch.org/docs/master/torchvision

extra:
  recipe-maintainers:
    - nehaljwani
    - hmaarrfk
    - h-vetinari
  feedstock-name: torchvision
