build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
workflow_settings:
  build_workspace_dir:
  - os: win
    provider: azure
    value: C:\\bld\\
  free_disk_space:
  - provider: azure
    value: quick
  pagefile_size:
  - os: linux
    provider: azure
    value: 10
  - os: win
    provider: azure
    value: 16
